### ISSUE TITLE
we don't need to module load singularity

### ISSUE THREAD

**Issue by soichih** [brainlife/app-dwiToDtiinit#1]
just a minor note..

we don't need to manually load singularity as it is expected to be on all resources (along with jq, git).

https://github.com/brainlife/app-dwiToDtiinit/blob/9f374bc0b6db15e7c520953c54937de22f613c45/main#L6

**Comment by bacaron** [comment]
thanks for the heads up! when did this change?

**Comment by soichih** [comment]
It's more like.. it gradually became an expectation. I should add a check to make sure singularity is available on all resources.
